# Generated by Django 5.2 on 2025-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('passs', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
